### ISSUE TITLE
Wyze HA not in Integrations after following install documentation

### ISSUE THREAD

**Issue by PhreakedoutClassic** [alanjames1987/Wyze-HA#12]
Wyze HA not in Integrations after following install documentation.  See attached screenshots, HACS is running, Wyze HA integration setup in HACS, rebooted HA. Under Configuration>Integrations>Search, the integration is not showing.  Please let me know if I am doing something wrong here...

![WyzeHA2](https://user-images.githubusercontent.com/88900553/142255627-488bedba-93a4-4924-b04e-676dfeffc58f.jpg)
![WyzeHA1](https://user-images.githubusercontent.com/88900553/142255629-86b133d2-d801-4ecd-bea8-ce6fed470811.jpg)

**Comment by PhreakedoutClassic** [comment]
Checking back 24 hours later, it appears to be there.  Perhaps a caching issue?  Closing out.

**Comment by alanjames1987** [comment]
Hey @PhreakedoutClassic that is strange and probably a caching issue. I'm unfamiliar with how HACS and HA cache integrations in the background. Whenever this happens to me I do a full restart by unplugging my HA computer and plugging it back in. That might not be possible in all situations but it works for me since I run my HA on a Raspberry Pi.
